Data-1289: Add alerting on data apis
viamrobotics/goutils pull request #189
Opened 2023-06-22 18:10 UTC by gloriacai01

Adding organization tag and view to grpc metrics in order to be able to add alerting policies for specific orgs.
Ticket: https://viam.atlassian.net/browse/DATA-1289

2023-06-22 18:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/viamrobotics/goutils?pullRequest=189) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/viamrobotics/goutils?pullRequest=189) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/viamrobotics/goutils?pullRequest=189) it.</sub>

2023-06-22 19:02 UTC, edaniels requested changes
I think you need to do this exact change but in app, not goutils. goutils is for our public, open source code for golang utilities

2023-06-23 16:11 UTC, gloriacai01 commented
> I think you need to do this exact change but in app, not goutils. goutils is for our public, open source code for golang utilities
@edaniels Do you have a recommendation of where in app I should be making this change?

2023-06-23 19:54 UTC, edaniels commented
talked offline to just use @AdamMagaluk's statz lib

2023-06-23 21:08 UTC, closed without merging