RSDK-9591 - Add Kill to ManagedProcess
viamrobotics/goutils pull request #399
Opened 2024-12-27 15:55 UTC by cheukt

This is part one of two PRs that will hopefully help with shutting down all module processes before viam-server exits.

This is still a draft as I'm looking for thoughts and ideas around making this better. 

The idea behind this is for a Kill() call to propagate from the viam-server, and we should not block on anything if possible. The `kill()`s here do not wait for the execed process to complete, and this is intentional - I couldn't find if syscall.Kill waits for completion, so did not use. I wasn't able to find documentation about whether `kill -9` blocks on the signal getting received or if it immediately returns, so opted for `.Start()` instead of `.Run()`, which means we do not `Wait()` for the process to return. This does mean that the assumption is that the viam-server ends immediately after and that the system will properly await the processes that we spawned to kill the managed process, otherwise those processes will be zombie'd. I can see changing it so that we do a `.Run()` instead, but might mean we would have to do the module process killing in parallel.

There is a todo to add Kill to the processManager, but a quick glance at how Close works for processManager makes me think that it should be a followup task

2024-12-31 21:14 UTC, dgottlieb commented on pexec/managed_process.go
> +	// Kill will attempt to kill the process group and not wait for completion. Only use this if
What's the story behind killing the process group? Is the `viam-server` part of the same process group? If we're intentionally trying to kill the viam-server + all modules running in one swift process group `kill -9`, what's the utility in adding this functionality to the goutils/managed process code?

2025-01-02 16:20 UTC, cheukt commented on pexec/managed_process.go
> +	// Kill will attempt to kill the process group and not wait for completion. Only use this if
the viam-server is not part of the same process group, each ManagedProcess is its own process group, I'm guessing the intention is to be able to `Kill` or `Stop` all spawned processes from one ManagedProcess at once

2025-01-02 16:21 UTC, dgottlieb commented on pexec/managed_process.go
> +	// Kill will attempt to kill the process group and not wait for completion. Only use this if
> the viam-server is not part of the same process group, each ManagedProcess is its own process group

I thought* that was a possibility. But I didn't see the code that did that. Is that in our code or the SDK side?

2025-01-02 16:25 UTC, cheukt commented on pexec/managed_process.go
> +	// Kill will attempt to kill the process group and not wait for completion. Only use this if
https://github.com/viamrobotics/goutils/blob/8961a203d9bc1ae41b4d750389a5f566e69a95bd/pexec/managed_process_unix.go#L69 sets the process group id, and since we didn't give the process group id a value, it will default to the child process' id https://pkg.go.dev/syscall#SysProcAttr.Setpgid

2025-01-02 16:29 UTC, benjirewis reviewed
Nice! Just some initial comments.

2025-01-02 16:29 UTC, benjirewis commented on pexec/managed_process_unix.go
> +// forceKill kills everything in the process group. This will not wait for completion and may result in a zombie process.
> a zombie process

I have heard this term used in a couple different ways. What do you mean by "zombie process"?

2025-01-02 16:29 UTC, benjirewis commented on pexec/managed_process_unix.go
> +	p.logger.Infof("killing entire process group %d", p.cmd.Process.Pid)
```suggestion
	p.logger.Infof("killing entire process group of process %d", p.cmd.Process.Pid)
```
ID is process ID not process group ID.

2025-01-02 16:29 UTC, benjirewis commented on pexec/managed_process_windows.go
> +	return exec.Command("taskkill", "/t", "/f", "/pid", pidStr).Start()
Did you test this on windows?

2025-01-02 17:05 UTC, cheukt commented on pexec/managed_process_unix.go
> +	p.logger.Infof("killing entire process group %d", p.cmd.Process.Pid)
the process group id is the process id, because of https://github.com/viamrobotics/goutils/pull/399#discussion_r1901046413

2025-01-02 17:06 UTC, cheukt commented on pexec/managed_process_windows.go
> +	return exec.Command("taskkill", "/t", "/f", "/pid", pidStr).Start()
not yet, I just copied this from kill() a bit above

2025-01-08 16:54 UTC, benjirewis requested changes
Could we add a test that a managed process that starts another process in the same process can both be killed by `Kill` (or `KillGroup` if you take my renaming suggestion)?

2025-01-08 16:54 UTC, benjirewis commented on pexec/managed_process.go
> +	Kill()
Should we call this `KillGroup`?

2025-01-08 16:54 UTC, benjirewis commented on pexec/managed_process_unix.go
> +// forceKill kills everything in the process group. This will not wait for completion and may result in a zombie process.
```suggestion
// forceKill kills everything in the process group. This will not wait for completion and may result in the kill becoming a zombie process.
```

2025-01-08 16:54 UTC, benjirewis commented on pexec/managed_process_unix.go
> +func (p *managedProcess) forceKill() error {
Should we call this `forceKillGroup`?

2025-01-09 15:02 UTC, dgottlieb approved these changes

2025-01-09 15:11 UTC, benjirewis approved these changes

2025-01-09 15:11 UTC, benjirewis commented on pexec/managed_process.go
> +	// Kill will attempt to kill the process group and not wait for completion. Only use this if
```suggestion
	// KillGroup will attempt to kill the process group and not wait for completion. Only use this if
```
Surprised lint passes.

2025-01-09 15:11 UTC, benjirewis commented on pexec/managed_process.go
> +func (p *managedProcess) KillGroup() {
```suggestion
// KillGroup kills the process group.
func (p *managedProcess) KillGroup() {
```
For lint.

2025-01-09 15:11 UTC, benjirewis commented on pexec/managed_process_unix.go
> +// forceKill kills everything in the process group. This will not wait for completion and may result the
```suggestion
// forceKillGroup kills everything in the process group. This will not wait for completion and may result the
```

2025-01-09 15:11 UTC, benjirewis commented on pexec/managed_process_windows.go
> +// forceKill kills everything in the process tree. This will not wait for completion and may result in a zombie process.
```suggestion
// forceKillGroup kills everything in the process tree. This will not wait for completion and may result in a zombie process.
```

2025-01-09 15:14 UTC, cheukt commented
you know, I'm surprised that it passes too

2025-01-09 23:42 UTC, merged